### PR TITLE
Make surveyor install on Rails 4.0

### PR DESCRIPTION
**Pull request by PragTob**
However it doesn't work, as there seems to be a problem with formtastic or something... at least I can not run the migrations.

Cheers,
Tobi

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like the main entry point only loads the engine if `Rails::VERSION::MAJOR == 3`.  I haven't tested, but you may need to change this also.

https://github.com/NUBIC/surveyor/blob/d27bdda0ee655da152fdbb181a35dfa1473be4d6/lib/surveyor.rb#L2

**Comment by ferrisoxide** [comment]
Am working on this myself. Have all the rspec's passing - now on to getting a full rails 4 app to verify against. See https://github.com/ferrisoxide/surveyor on the develop branch. Very much a work in progress

**Comment by PragTob** [comment]
Cool @ferrisoxide - thanks for chiming in. Would be cool to hear some statements from the maintainers.

**Comment by yoon** [comment]
Our group is hard at work on one of the apps that uses surveyor, and we haven't had a chance to take a look at this yet. Thanks for the contribution!

**Comment by caboteria** [comment]
I have added more Rails4 fixes to @ferrisoxide's work, which was a great start.  The rspec tests now pass and we're down to a single deprecation warning.  I opened a pull request back to his fork, so hopefully he can be a point of focus for Rails4 changes.  If he opts not to, I'll do it.

**Comment by ferrisoxide** [comment]
Hi @caboteria. I'd love to help out, but I'm not sure I can provide consistent support for the Rails 4 changes (and I don't want to disappoint anyone). But thank you for asking.

I am planning on doing some extra work - mainly to get rid the requirement for the `protected_attributes` gem - and I'll let you know when I've done so. But I can't say when I'll get around to it. :(

**Comment by caboteria** [comment]
Thanks for getting the Rails4 ball rolling @ferrisoxide, I'll keep chipping away at it.  If you get the protected_attribute stuff worked out, please send me a pull.

**Comment by devilankur18** [comment]
+1

**Comment by ferrisoxide** [comment]
I'll have some time to work on the Rails 4 port next week. Sorry for the general slackness - just busy on other things.  Good work @caboteria for pushing this along.

**Comment by yoon** [comment]
@ferrisoxide and @caboteria thanks for your contributions! See the rails4 branch.

**Comment by caboteria** [comment]
Great to see activity on this, thanks @yoon.  I'd be curious to find out what your plans are for Rails 4 (and I think others would be, too).

The changes I'm using to get Surveyor to work with Rails 4 are in the pull request in issue #468.  Hope they're useful to you.

**Pull request closed without merging**
