### PR TITLE
Dropdowns inside of repeaters display as radio buttons

### PR DESCRIPTION
**Pull request by jdzak**
When a dropdown exists inside of a repeater, it will display as radio buttons.

<pre>
survey "Movies" do
  section "Preferences" do
    repeater "What are you favorite genres?" do
      q "Make", :pick => :one, :display_type => :dropdown
      a "Action"
      a "Comedy"
      a "Mystery"
    end
  end
end
</pre>

### CODE REVIEW

**Comment by yoon** [comment]
Thanks!

**Comment by pcasa** [comment]
Getting this problem with groups.  Am using jquery.  does that make a difference?

**Comment by yoon** [comment]
This should be fixed in the most recent version of surveyor - have you tried `bundle update surveyor`? Surveyor also uses jquery and jquery tools, so that shouldn't be an issue.

**Comment by pcasa** [comment]
fresh install, as of yesterday.

Forgot to mention, using rails 3 branch.

**Comment by yoon** [comment]
I've brought the rails3 branch up to speed with the master branch, and I see a dropdown inside of the repeater.

**Comment by pcasa** [comment]
Sorry yoon, but when trying to update keep getting:

Could not find gem 'surveyor (>= 0.20.0)' in git://github.com/breakpointer/surveyor.git (at rails3).
Source contains 'surveyor' at: 0.16.1

gem update surveryor kept saying nothing to update so tried to force by changing my gemfile to:
gem 'surveyor', '>= 0.20.0', :git => 'git://github.com/breakpointer/surveyor.git', :branch => 'rails3'

**Comment by yoon** [comment]
I would suggest trying it without the version number, just the branch.

Mark A. Wimbiscus Yoon
Systems Analyst/Programmer
Northwestern University Clinical and Translational Sciences Institute (NUCATS)
312-503-2343
yoon@northwestern.edu
http://www.nucats.northwestern.edu

On Thu, Jul 21, 2011 at 9:14 AM, pcasa
reply@reply.github.com
wrote:

**Comment by yoon** [comment]
Also, the url is now github.com/NUBIC/surveyor.git

Mark A. Wimbiscus Yoon
Systems Analyst/Programmer
Northwestern University Clinical and Translational Sciences Institute (NUCATS)
312-503-2343
yoon@northwestern.edu
http://www.nucats.northwestern.edu

On Thu, Jul 21, 2011 at 9:14 AM, pcasa
reply@reply.github.com
wrote:

**Comment by pcasa** [comment]
That was it.  My mistake.

**Pull request closed without merging**
