### PR TITLE
Add input mask for text entry fields

### PR DESCRIPTION
**Pull request by jdzak**
Having a way to specify an input mask for text boxes would provide users a visual cue when entering certain types of data (e.g. phone numbers or zip code), and it would constrain what is entered to either alpha/numeric/both as well as the length of input. 

One possible way to implement this would be to add a property on answer..

<pre>
q 'If you have a phone the user would see..
a :string, :input_mask => '(999)999-9999'

# Produces
# (___) ___ - ____
</pre>

As an extra, it would be nice to control the placeholder character. So for example, instead of having an underscore as the placeholder, you could use 'Y'  if you need the user to enter a year.

### CODE REVIEW

**Comment by yoon** [comment]
Thanks for this - Some features are failing against the current master. A cucumber feature would be helpful to demonstrate how this is to be used. Maybe even an example in the kitchen sink.

Answer#placeholder might be ambiguous (confused with something like #hint). I propose we rename it to #input_mask_placeholder as it is really tied to that implementation. The limit might be removed in the future, so it might be good to leave it off for now.

Another note, the translations branch will soon be merged, which removes the a_text helper. It's not in master yet, so depending on the timing, I can take on this one.

**Comment by jdzak** [comment]
@yoon I implemented all your suggestions. Ready for review.

**Pull request merged**
