### PR TITLE
support translations of surveys via yaml

### PR DESCRIPTION
**Pull request by yoon**
we propose placing translations in a yaml file, to be processed and stored in the database at survey dsl parse time, so that versions remain in sync. this will require a survey_translations table, and modifications to all the methods that display text specified in the survey and displayed to the user. it may also require modifications of input masks, since different locales specify dates in different ways.

example yaml:

```
es:
  2a:
    text: "Por favor, explique por qué no te gusta este color"
    answers:
      1:
        text: "explicación"
        help_text: "Por favor dé una explicación para cada color que no le gusta"

```

### CODE REVIEW

**Comment by yoon** [comment]
@rsutphin Responded to your comments, which seem to have disappeared due to to the forced push.

**Comment by hannahwhy** [comment]
How does this interact with Handlebars helpers and other generated content that requires internationalization?  

Consider the question text `Is your monthly income greater than {{income}}?`.  Does this imply the existence of a YAML fragment like

``` yaml
# fr
questions:
  income:
    text: "Est votre revenu mensuel est supérieur à {{income_fr}}?"
```

as well as a corresponding `income_fr` helper, where the `income_fr` helper would format (e.g.) `75,000 USD` as `75.000 USD` (and, I suppose, do USD -> EUR conversion if you were feeling really fancy)?

How will this work with languages that read right-to-left, e.g. Arabic?  Do you need to insert LTR/RTL marks to keep the Handlebars helpers straight?

**Comment by hannahwhy** [comment]
Another comment on the YAML:

There is unnecessary redundancy in the structure.  In NCS we see many questions that -- while they ask different things -- have the same (or very similar) set of answers, i.e. "Yes", "No", "Refused", "Don't Know".  It should not be necessary to specify separate translations for those answers, even though they have the same text.  

This can be ameliorated to some degree using YAML anchors and references, but that does not always work: consider, for example, two answer lists that contain the same elements but in permuted order, or two answer sets that share some but not all elements.

[GNU gettext](http://www.gnu.org/software/gettext/), a [Ruby gettext implementation](https://github.com/ruby-gettext/gettext), and [other gettext implementations](http://en.wikipedia.org/wiki/Gettext#Implementations) eliminate this redundancy by mapping a source string to a target string.  (There are more rules for more complex cases, but that basic structure suffices for many use cases.)  This approach also simplifies translation lookup, because you don't need to know anything about question, answer, section, or group references.

**Comment by jefflunt** [comment]
Question about reducing redundancy:

Can this work in cases where the source text is translated in a way that is dependent on the question/context of the answer? Direct, word-for-word translations miss the context in which a given text is provided, and so even strings that appear simple and short in English may get translated to different destination strings depending on the recommendation of the translator and the context in which they are provided.

@yipdw - are you recommending automatic translations, but retaining support for overriding those automatic translations where a human translator believes that a more subtle (and more accurate) translation is necessary?

For example, the answer "Yes" in one answer in English, depending on the recommendation of the translator might result in a word or phrase meaning "Yes" in the destination language, but may also need to be translated as something closer to "I agree", or "I don't disagree" or other language-specific subtleties that we haven't thought of.

I think it's useful to save translator's time to reduce redundancy, but only if they retain the ability to specify exceptions where their expertise should override this automation.

**Comment by hannahwhy** [comment]
> Can this work in cases where the source text is translated in a way that is dependent on the question/context of the answer?

Yes.  The gettext model works in that case.

The source string (or msgid) is the text inputted by the programmer.  Typically, this is English text and is just passed through for the English text domain.  However, that's not required; applications that use the gettext model (FYI: the vast majority of UNIX applications fall into this category) can treat English as another target language.

This means that you can, if necessary, write something like this:

``` ruby
a_1 "yes_agree"
a_2 "No"
```

For English:

```
"yes_agree": "Yes"
```

For Spanish (maybe):

```
"yes_agree": "acuerdo"
```

In this case, "yes_agree" ends up with different translations.  "No" is the same in both domains.  (This is the default behavior of gettext: if you don't specify a translation in a target domain, the source string is passed through.)

In the case where _every answer_ requires this sort of mapping, yes, you do end up with an extra level of indirection to read the English text.  However:
1. If you require that level of nuance throughout your survey, you're better off with symbolic keys as stand-ins anyway, as they let translators and other writers adjust text with less burden on the programmer.
2. I would like to know just how often that _really_ happens.  @flockom showed me some Spanish NCS instrument data and it did not appear to exhibit properties requiring additional nuance.

> @yipdw - are you recommending automatic translations, but retaining support for overriding those automatic translations where a human translator believes that a more subtle (and more accurate) translation is necessary?

No, gettext does not do that; translation is still done by a human.  gettext merely extracts source strings, prepares and keeps translation files up-to-date, and provides an interface to map a source string to a string in the target text domain.

The [GNU gettext manual](http://www.gnu.org/software/gettext/manual/html_node/index.html) discusses this in more detail.  There's also some information about [writing translatable strings](http://www.gnu.org/software/gettext/manual/html_node/Preparing-Strings.html#Preparing-Strings).

**Comment by hannahwhy** [comment]
More:

> I think it's useful to save translator's time to reduce redundancy, but only if they retain the ability to specify exceptions where their expertise should override this automation.

In the case of NCS Navigator, we're not sending surveys to translators; we're extracting data from pre-translated surveys.  So this model actually could mean a little more work in that specific case.

However, yes, eliminating redundancy makes life easier for other Surveyor users who may not be approaching translation the same way the NCS Navigator project is.  This model is also significantly simpler than the current implementation, because it requires only a single scalar to establish a mapping.

**Comment by jefflunt** [comment]
Yeah, I'm sorry I didn't mean automatic translations as in translating the meaning of words. I assumed a human would always be involved. I meant the ability for the person to specify when an auto-mapping between a source and destination text are mapped to one another.

I'm more questioning the need to provide an auto-mapping function (for de-duplication of work) if a human is ultimately responsible for QAing a given translation.

**Comment by hannahwhy** [comment]
The method I propose is no more automatic than the method in this pull request; all I really am changing is the scope of the translation identifiers.  I'll prepare an example implementation in a bit.

**Comment by hannahwhy** [comment]
> I'll prepare an example implementation in a bit.

This turned more into a "hey, I bet we can just use gettext for Surveyor directly" thing; I should have something to show soon.  Using gettext directly reaps the benefits of standardization, i.e. it lets people use already-existing tools written for the gettext model.

[GNU gettext's capability to resolve ambiguities using contexts](http://www.gnu.org/software/gettext/manual/html_node/Contexts.html) might also be useful.  (ruby-gettext implements a similar API.)  The survey/section/question/answer hierarchy in the proposed YAML structure can be re-purposed as a gettext context, with the important difference that the context only needs to be specified when ambiguities exist.

**Comment by hannahwhy** [comment]
Having written all that, I should answer the last question posed here:

> I'm more questioning the need to provide an auto-mapping function (for de-duplication of work) if a human is ultimately responsible for QAing a given translation.

Translators are responsible for QA, but they're also responsible for translation.  That's a lot of work, and dealing with the drudgery of duplication is an additional annoyance that they shouldn't have to deal with, especially not when there are tools out there that could eliminate that problem.

The tools I've mentioned are mature internationalization solutions that are in wide use and -- as far as I can tell -- eliminate duplicate work where possible and provide ways to deal with context-dependent translations that are sufficient for Surveyor's needs.  Am I missing something?

**Comment by seanvolution** [comment]
Just to be clear about redundancy and NCS: the translation files are complete replicas of the original instruments.  In many cases where answers or instructions are not intended to be read aloud, they are not translated at all.  The translation will then be a mixture of original text and translated text.  

Duplication in this use case is not drudgery – it has already been completed.  The drudge work would actually be de-duplicating files rather than reading them in as-is.

**Comment by hannahwhy** [comment]
> Just to be clear about redundancy and NCS: the translation files are complete replicas of the original instruments. In many cases where answers or instructions are not intended to be read aloud, they are not translated at all. The translation will then be a mixture of original text and translated text.

Right, and this proposal should work in that case too, though one would have to take a different path towards building a translation.  I don't yet know if it's that much more work, but I can investigate that.

In any case, I was under the impression that this was meant to be an internationalization system for Surveyor meant for general use, not just NCS, and from that perspective there are benefits to 
1. not having to translate source strings more than once unless you absolutely need to, and
2. being able to hook into existing tools to manage translations.

**Comment by seanvolution** [comment]
There is also benefit to
1. supporting the use case at hand and 
2. not investing effort in use cases that may or may not present themselves at a future time.

**Comment by rsutphin** [comment]
> How does this interact with Handlebars helpers and other generated content that requires internationalization?

It could work the way you outline (with locale-specific helper names), or the Mustache context could be written such that it is locale-aware itself, or a combination of the two. The proposed implementation leaves this up to the adopting application.

> How will this work with languages that read right-to-left, e.g. Arabic? Do you need to insert LTR/RTL marks to keep the Handlebars helpers straight?

I don't know, but I do know that the answer will either be "yes" or "no". If it comes up on the list, we can find out and document it. (I imagine that's going to be dependent on how the Mustache implementation works.) I don't think that this detail affects this feature one way or the other.

**Comment by rsutphin** [comment]
Re: gettext.

I'm no gettext expert, but it seems to me that most of the more complex behaviors in gettext (e.g., pluralization) require collaboration between the translation and the software which is embedding the translated values. I.e., Surveyor would have to be aware if a particular token was scoped, or pluralizable, or whatever. Since that can't happen, we're just talking about using gettext's basic substitution feature, correct? (Maybe with section/question scoping, but nothing specific to the way the tokens are used in the survey.)

gettext's basic substitutions take a source string and associate it with a translated string. This can either be done by defining a token and providing string values for it in all supported languages or by taking a string in the default language and associating it with the translation in all other languages. So (to reuse @yipdw's example), the token example would be:

```
# Survey
a_1 'yes_agree'

# English translation
'yes_agree': 'Yes'

# Spanish translation
'yes_agree': 'Acuerdo'
```

And the default language example would be:

```
# Survey; default language here is English
a_1 'Yes'

# Spanish translation
'Yes': 'Acuerdo'
```

As @yipdw notes, you can mix these in the same application. However, every translated item has to be one or the other. So say you have this question:

> "In the last 6 months, have any additions been built onto your home to make it bigger or renovations or other construction been done in your home? Include only major projects. Do not count smaller projects, such as painting, wallpapering, carpeting or re-finishing floors."

With a gettext-based Surveyor translation system, you have two options:
- Include this entire 271 character question, exactly, in each translation file. Every time you fix a typo in the default language, you'll have to remember to update every translation also.
- Replace the question with a unique token. This makes the survey harder to read and understand — while coding it / reviewing it in the default language, you have to refer to a separate file to understand the actual questions.

Neither of those are particularly great options. Each of them is congnitively harder to deal with than having duplicated strings for common answers in the translation files. [This is no knock against gettext — it's just primarily intended for applications where the bulk of the translated strings are short (e.g., user interface elements or status/error messages).]

There are a couple of other reasons why I don't think that gettext is a good choice:
- gettext seems to use "po" files which have to be compiled using a separate build process. The proposed solution uses YAML files that don't need to be compiled. Fewer build steps = less stuff to break.
- The proposed solution uses files which are analogous to the YAML files used by Rails' native localization system and so will be conceptually familiar to Rails developers.
- Because surveys are versioned, the translations need to be versioned also. I imagine we could figure out a way to make this work with ruby-gettext, but it doesn't seem to be the easiest thing.

Did I misunderstand something about gettext?

**Comment by hannahwhy** [comment]
> With a gettext-based Surveyor translation system, you have two options:
> Include this entire 271 character question, exactly, in each translation file. Every time you fix a typo in the default language, you'll have to remember to update every translation also.

I have written a program that automatically does this for Surveyor surveys.  Specifically, it generates POTs, which can spawn and/or update existing POs via `msginit` or `msgmerge`.  It can be integrated into a build process to check the status of translations.

The program is here: https://github.com/yipdw/imperator/blob/master/imperator-xgettext
It produces output like this: https://gist.github.com/yipdw/5080328

While the program lives in the `imperator` repository, it can be extracted.  I can write up a gist describing its use in a gettext-based translation system tomorrow morning (or just describe it in person, which may be faster).

> Replace the question with a unique token. This makes the survey harder to read and understand — while coding it / reviewing it in the default language, you have to refer to a separate file to understand the actual questions.

Right, I don't think that's a good idea either.  That said, message contexts can eliminate the need to fall back to tokens in such cases; the above gist has some examples of that.

> gettext seems to use "po" files which have to be compiled using a separate build process. The proposed solution uses YAML files that don't need to be compiled. Fewer build steps = less stuff to break.

You can compile po files to mo files, but you don't have to.  ruby-gettext requires MO compilation, but there are Ruby gettext implementations that don't, e.g. https://github.com/grosser/fast_gettext.  

On a tangent, there's also a Javascript gettext implementation that doesn't require MO compilation, which I used (along with POEditor and the above `imperator` programs) to build this: https://s3.amazonaws.com/nw-depot/surveyor-translation/survey.html

> The proposed solution uses files which are analogous to the YAML files used by Rails' native localization system and so will be conceptually familiar to Rails developers.

The YAML structure may be more familiar to Rails developers, but po files are supported by a large number of applications already in use by translators.

> Because surveys are versioned, the translations need to be versioned also. I imagine we could figure out a way to make this work with ruby-gettext, but it doesn't seem to be the easiest thing.

Survey versioning exists in two places, as I understand it:
1. The survey source file.  In this case, the po can be versioned like any other source file.
2. The representation of the survey in the database.  To handle this, here's one possibility (and by no means the only one):  You could keep the po as a blob, either in the surveys table or in an associated table.  Putting the po blob in the surveys table directly ties the po blob to the survey version; the associated table approach can be implemented by (perhaps) a composite primary key on survey ID and survey version.

**Comment by hannahwhy** [comment]
> There is also benefit to
> 1. supporting the use case at hand and 
> 2. not investing effort in use cases that may or may not present themselves at a future time.

I agree on both points, but I also think that adopting existing solutions where possible is a good idea: by doing so, you get the benefits of the work that has been invested in that prior solution.  You also, of course, get the baggage associated with that prior solution; however, I think a gettext-based approach is easier to work with.

I intend to discover how difficult it is to write a transformation process for the NCS instrument translations following this scheme, and the best way I know of to measure that is to write a program to do it.  Such a trial would be done on my own time; all I'd need for it are the source documents.

**Comment by rsutphin** [comment]
> I have written a program that automatically does this for Surveyor surveys. Specifically, it generates POTs, which can spawn and/or update existing POs via msginit or msgmerge. It can be integrated into a build process to check the status of translations.

Even if you can automatically determine which elements are missing translations, you still have the problem I described. Every time you fix a typo in any of dozens of hundred-character questions, you have to go find all their existing translations files and remap the question translation. I continue to argue that this is more cognitive load than having to copy-paste duplicate responses sometimes.

> The YAML structure may be more familiar to Rails developers, but po files are supported by a large number of applications already in use by translators.

Two notes on this:
- You've mentioned that there are a large number of applications in use by translators a couple of times. Can you provide some links? The only utilities I've found in looking around are tools to help you extract strings that need to be translated. As you've already noted, those tools don't help with Surveyor.
- Presumably the person doing the translations for a survey embedded in a Rails app will also be doing translations for the Rails app itself. (Leaving aside cases like NCS Navigator, where the translation is done by people who don't care about the software at all.) When we are talking about Surveyor, which is purely a Rails add-on, doesn't the familiarity argument push in the direction of using something like Rails' localization system? Gettext may be the most standard mechanism for all software everywhere, but for Rails applications surely Rails' localization mechanism is the standard mechanism.

**Comment by rsutphin** [comment]
Also, while the proposed solution will require redundant answer translations in some cases, I can think of several ways it could be modified later if this becomes a real problem in practice without breaking backwards compatibility.

I think the gettext question comes down to: given the acknowledged mismatches between Surveyor's translation needs and the gettext/PO structure, is there an overridingly compelling reason to have Surveyor natively consume PO files for translation?

**Comment by yoon** [comment]
surveyor supports RTL languages, see [lib/generators/surveyor/templates/config/locales/surveyor_he.yml](https://github.com/NUBIC/surveyor/blob/958299c3a45d6bf650c0d3078adeee2adc920e9a/lib/generators/surveyor/templates/config/locales/surveyor_he.yml) and [/lib/generators/surveyor/templates/surveys/translations/languages.he.yml](https://github.com/NUBIC/surveyor/blob/958299c3a45d6bf650c0d3078adeee2adc920e9a/lib/generators/surveyor/templates/surveys/translations/languages.he.yml)

**Comment by hannahwhy** [comment]
> You've mentioned that there are a large number of applications in use by translators a couple of times. Can you provide some links? The only utilities I've found in looking around are tools to help you extract strings that need to be translated. As you've already noted, those tools don't help with Surveyor.

Sure.  I used [POEdit](http://www.poedit.net/download.php) that example; others are mentioned at http://drupal.org/node/11131.

These programs do more than string extraction.  POEdit, in particular, shows a source string, its target, and its context (both in the source file and with any manually-added `msgctxt`s).  It also shows whether or not a translation is out-of-sync with its source, marked as fuzzy, etc.

**Comment by hannahwhy** [comment]
> Even if you can automatically determine which elements are missing translations, you still have the problem I described. Every time you fix a typo in any of dozens of hundred-character questions, you have to go find all their existing translations files and remap the question translation.

That's `msgmerge`'s job; it contains an algorithm to map those sorts of changes to existing translations.

> I think the gettext question comes down to: given the acknowledged mismatches between Surveyor's translation needs and the gettext/PO structure, is there an overridingly compelling reason to have Surveyor natively consume PO files for translation?

I'm not sure there is a mismatch, but I think I ran out of reasons to continue gettext advocacy -- software that depends on this feature as implemented in this PR is already being written, and I cannot realistically replicate the work of many people to demonstrate the feasibility (or infeasibility) of the gettext approach.

**Pull request closed without merging**
