### PR TITLE
Use UTC for timestamps in JSON; make completed_at nullable.

### PR DESCRIPTION
**Pull request by hannahwhy**

### CODE REVIEW

**Comment by hannahwhy** [comment]
An FYI: This problem was observed in NCS Core. The database used in Surveyor's integration tests stores timestamps in UTC, so replicating this issue in that environment was difficult enough that I decided to put it off for now.

It's possible that the correct place to fix this is not in Surveyor, but rather in Core.

**Comment by jdzak** [comment]
My questions/concerns..
1. Existing rails app would have to set the timezone if it's not already (which could corrupt existing dates)
2. Do clients send the time in utc or can they use localtime as long as they include their offset?
3. Do any applications expose completed_at, modified_at, updated_at as editable in the interface? If so we'd wouldn't want to corrupt the date.

**Comment by hannahwhy** [comment]
1. What Rails applications do not store timezone data?  The default configuration for Rails applications since the 2.x days has been to store timezone information with timestamps.  (Also, IMO, if someone has been running an application that _doesn't_ store timestamps with timezones, they already _have_ bad data.)
2. If a client wishes to send JSON conformant to the schema, it should not use anything but UTC.  JSON Schema draft 03 recommends UTC times; see http://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23.  Draft 04 might address this,  but draft 04 hasn't been finalized.  Clients _can_ send other formats, but I've seen validators interpret "SHOULD" as "MUST".  (The `json-schema` gem does this, for example.)
3. Provided that the source timestamp's timezone is known, a UTC conversion does not corrupt the timestamp.  A front end displaying these timestamps will have to be adjusted to show the timezone and/or adjust for the user's timezone preference.

**Comment by jdzak** [comment]
1. So i guess I wasn't clear what I meant, I was just more concerned with existing applications not having configured  the default timezone (so it defaults to UTC).  This change would force applications to configure their timezone, (although I suppose they wouldn't have to configure it if they don't use the api).  But I guess this is just a normal progression if users want to use timezone sensitive data.
2. Sounds good.
3. Right, for applications already supporting timezones in the UI that's true.

**Comment by hannahwhy** [comment]
I'm going with an alternative approach: 
1. don't use JSON Schema's definition of `date-time`
2. encode the W3C's "complete date plus hours, minutes and seconds" definition (http://www.w3.org/TR/NOTE-datetime)

**Pull request closed without merging**
