### PR TITLE
Support asset pipeline precompilation

### PR DESCRIPTION
**Pull request by hannahwhy**
This is a simplification of a patch by @gaurish (#314).  See commit messages for details.

The gist: this patch set fixes asset pipeline precompilation for Rails >= 3.1 applications that use the asset pipeline.  Rails 3.0 applications are not affected.

### CODE REVIEW

**Comment by gaurish** [comment]
This looks lot cleaner than my implementation. But can you please merge this with existing PR #314?

Further, I have added you as a Collaborator on [gaurish/surveyor](https://github.com/gaurish/surveyor) as we could hack on this together. Thanks

**Comment by hannahwhy** [comment]
Hi @gaurish,

Sure, I can merge this, though I'm not sure what you mean.  Do you want me to submit my changes as a branch to your fork?

**Comment by gaurish** [comment]
Yes. so we could hack this together & avoid duplication of work. But's only a suggestion :)

**Comment by hannahwhy** [comment]
Sure, I'll get on that in a bit.

**Comment by yoon** [comment]
I have a full solution to this as well, and am currently working on merging all three approaches.

**Pull request closed without merging**
