### PR TITLE
Fixed a problem with correct_answer not refering to the right answer under "certain" circumstance

### PR DESCRIPTION
**Pull request by jadetr**
In the Question model, the reference to correct_answer should be belongs_to as the correct_answer_id is located in the questions table.

### CODE REVIEW

**Comment by jdzak** [comment]
@jadetr thanks for the pull request.  Could you provide a survey where correct answer is incorrectly referenced?

**Comment by jadetr** [comment]
Here we are!

survey "survey", :description=>"Desc" do

  section "Section", :description=>"desc", :display_order=>1 do

```
q_1 "Q1?", :pick=>"one", :display_order=>1, :correct => '2'
a_1 "a1", :display_order=>1
a_2 "a2", :display_order=>2
a_3 "a3", :display_order=>3
a_4 "a4", :display_order=>4


q_2 "Q2 ?", :pick=>"one", :display_order=>2, :correct => '2'
a_1 "a1", :display_order=>1

a_2 "a2", :display_order=>2

a_3 "a3", :display_order=>3

a_4 "a4", :display_order=>4
```

  end
end

Code in my controller 
#Load Q1
q = Question.find(229) 
Rails.logger.debug "correct_answer_id: #{q.correct_answer_id}, correct_answer.id:#{q.correct_answer.id}"
correct_answer_id: 1087, correct_answer.id:1088

**Comment by rsutphin** [comment]
@jadetr I also think you for your patch. Could you please provide a spec or feature that fails without the fix present? Then we should be able to take care of this once and for all.

**Comment by jadetr** [comment]
@rsutphin

Hello,

I'm not used to spec and/or feature. I won't have time to learn this to 
help further.

Next time, I'll take some time to learn this.

Best regards,

Jade

**Pull request closed without merging**
