### PR TITLE
JSON serialization does not include reference identifiers for answers in question groups

### PR DESCRIPTION
**Pull request by rsutphin**
Solve the issue in the title and verify that all other attributes for questions/answers/dependencies/etc that are serialized outside of question groups are serialized inside of question groups also.

### CODE REVIEW

**Comment by rsutphin** [comment]
Ready for review.

**Comment by rsutphin** [comment]
Apologies for the mess. I figured the PR would clean up after a forced push, but it seems like not. Anyone know a way to get the dead commits out of here?

**Comment by yoon** [comment]
I'll merge it manually.

**Comment by rsutphin** [comment]
The merge will be fine (you can see in the commits tab that only the desired commits are in the branch), it's just this PR page that is a mess.

**Pull request merged**
