### PR TITLE
Prevent duplicates by pre-assigning UUIDs to responses

### PR DESCRIPTION
**Pull request by rsutphin**
This branch implements the duplicate prevention strategy outlined in #328. This is a wide-ranging change, affecting the data model, many of the views, the implementation of PUT for the response set resource, and more.

This branch also includes two related but not mandatory changes which could be factored out if desired:
- Switching to chrome as the default browser for selenium. There are now many integration tests that rely on the javascript change event being fired for correctness. Firefox does not fire this event when it is in the background, which is annoying for long-running test suites. The downside of using chrome is that it does require additional software to be installed (chromedriver; available from homebrew). More notes on this in the README.
- Removing blockUI. AFAIK, this was only added as a way to prevent duplicate responses. Since duplicate responses are not possible with this branch, it doesn't seem necessary any longer.

### CODE REVIEW

**Comment by mgurley** [comment]
This is a big change to surveyor.  It will make it difficult for projects that have extended surveyor to upgrade.  If we are going to do a big refactoring, I think we should do it in the direction of changing surveyor to submit update requests using the standard Rails nested attributes data structure.  If we were writing surveyor from scratch today, is this how we would implement it?

For the BTI  Intake Form project, we were experiencing duplicate responses as well. We identified that the duplicates were coming from users pressing the enter key/go button inside of text boxes.  So we decided to address that specific problem with the following changes:
- Converted  the menu items, next section and the previous section buttons to links.
- Added a hidden submit tag as the first input element within the #survey_form that returns false on click.
- Attached a handler to the submit event of the #survey_form that returns false.
- Unbind the same handler on the click event of the #finish_button.

No duplicate responses have been created in our database after making these changes.

**Comment by rsutphin** [comment]
Thanks for the review.

> It will make it difficult for projects that have extended surveyor to upgrade.

Is there a specific extension type that it will make more difficult? The expected received data is the same as in previous versions of Surveyor, except that it wants the `api_id` instead of the `id`. I would be interested to hear about real-world extensions that are affected by this.

> I think we should do it in the direction of changing surveyor to submit update requests using the standard Rails nested attributes data structure.

This is actually how it used to work (though it applied a series of opaque transfomations to the submitted form data to get there). You can only use the full nested attributes structure if you are updating things based on their primary keys. Since lack of foreknowledge of the primary key is the way parallel requests trigger #328 in the first place, this isn't a tenable solution.

However, the submitted solution does use `update_attributes` as much as possible -- it locates/creates individual Responses via the api_id, but sets their attributes using the usual ActiveRecord mass assignment procedure. This should be amenable to custom response attributes in exactly the same way as the existing implementation.

> If we were writing surveyor from scratch today, is this how we would implement it?

If I were writing surveyor from scratch today, I think I might have a somewhat different data model. However, I would still be inclined to try to guarantee that duplicates couldn't be created on the server side rather than through client-side trickiness.

> So we decided to address that specific problem with the following changes

Indeed, this is the path we've been following with Surveyor for some time. We locate some specific way that duplicates can be created in the UI, then re-engineer that part of the UI so that it doesn't issue parallel requests. Then we find another way duplicates can be created, and we re-engineer that part of the UI, and on and on. Each time we add a new control or change the way the UI works, we have to ensure that it doesn't issue parallel requests. Sometimes we forget, and then there's bad data.

My proposed solution _guarantees_ no duplicate responses, ever. Thus it will allow the UI to be simpler and more flexible. It will allow adopting applications to more radically change the UI without being aware that they need to be careful about issuing parallel requests. And it does this with limited changes to the outwardly-facing parts of Surveyor's API.

**Comment by kumbafu** [comment]
I like the idea of stopping duplicate requests server side - it's a big change, but it ensures data integrity which I think makes it worth it.

RE: Block UI - There's another rare (i've only seen it twice) but serious problem that block UI prevents. If changes made to the same question are processed server side out of sequence, the data recorded will be false  and won't be indicated on the UI - unless the user refreshes the page.

**Comment by rsutphin** [comment]
> RE: Block UI - There's another rare (i've only seen it twice) but serious problem that block UI prevents. If changes made to the same question are processed server side out of sequence, the data recorded will be false and won't be indicated on the UI - unless the user refreshes the page.

It is generally true that async requests can end up being processed out of sequence. Block UI prevents this in the same way that it prevented duplicates from being created — for only the fraction of interactions that are blocked by Block UI. If this is a serious problem (and it is), it needs to be taken care of in a way that guarantees correctness without requiring every UI control author to be aware of the potential problem.

I can restore Block UI if it's the consensus that that's what's appropriate, but I wouldn't call it a fix for the (rare but serious) problem @kumbafu describes.

**Pull request merged**
