### PR TITLE
Ref. 454 - Fixes migration.

### PR DESCRIPTION
**Pull request by jefflunt**
Fixes typo in create survey translations migration.

### CODE REVIEW

**Comment by jdzak** [comment]
:cake:

**Comment by rsutphin** [comment]
(#454 to get xref in other ticket)

**Comment by rsutphin** [comment]
The bad migration is in a released version of Surveyor (as @normalocity noted). We should probably also send a note to the list to tell people who have upgraded to an affected version that they should manually edit this migration. It should be noted in the changelog also.

**Comment by jefflunt** [comment]
Is it feasible to alter the generators for the next surveyor release to correct the typo in existing installations, so that upon upgrade to the next surveyor release, anyone who didn't get an email notification about the issue is automatically covered?

**Comment by rsutphin** [comment]
> Is it feasible to alter the generators for the next surveyor release to correct the typo in existing installations, so that upon upgrade to the next surveyor release, anyone who didn't get an email notification about the issue is automatically covered?

It's possible, but I don't know that it's worth the labor/complexity. It would require special-case code in the generators which couldn't ever really be removed. (Who knows how long someone's going to wait to upgrade from 1.4.0? There's no requirement that you go from 1.4.0 to 1.4.0++.)

**Pull request merged**
